version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Thanhnhan1409
      MYSQL_DATABASE: vivaflow
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nest-app:
    build:
      context: .
      target: production
    container_name: nest-app
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql-data: